baseURL = "http://ingrain.redsift.io/"
languageCode = "en-us"
title = "InGRAINd"
enableGitInfo = true
theme = "book2"
publishDir = "../"

[params]
MainMenuBundle = "/main-menu"
BookMenuBundle = "/docs/menu"
BookLogo = "svg/logo.svg"
